import React, { useState } from 'react';
import {
  BarChart3,
  TrendingUp,
  Download,
  Calendar,
  CheckCircle2,
  AlertTriangle,
  Award,
  DollarSign,
  Package,
  Layers,
  Printer
} from 'lucide-react';
import {
  AreaChart,
  Area,
  BarChart,
  Bar,
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  PieChart,
  Pie,
  Cell,
  Legend
} from 'recharts';
import { monthlySalesData, categorySalesData } from '../mockData';
import { Product, Order, InventoryItem, Supplier, VATask } from '../types';

interface ReportsViewProps {
  products: Product[];
  orders: Order[];
  inventory: InventoryItem[];
  suppliers: Supplier[];
  tasks: VATask[];
}

const CATEGORY_COLORS = ['#3b82f6', '#10b981', '#f59e0b', '#8b5cf6', '#ec4899'];

export const ReportsView: React.FC<ReportsViewProps> = ({
  products,
  orders,
  inventory,
  suppliers,
  tasks,
}) => {
  const [reportPeriod, setReportPeriod] = useState('Last 6 Months');

  // Computed metrics
  const totalRevenue = orders.reduce((sum, o) => sum + (o.paymentStatus === 'Paid' ? o.amount : 0), 0);
  const totalUnitsSold = inventory.reduce((sum, i) => sum + i.unitsSold, 0);
  const publishedProducts = products.filter((p) => p.status === 'Active').length;
  const catalogCompletionRate = Math.round((publishedProducts / (products.length || 1)) * 100);
  const avgSupplierScore = Math.round(
    suppliers.reduce((sum, s) => sum + s.performanceScore, 0) / (suppliers.length || 1)
  );
  const completedTasksCount = tasks.filter((t) => t.status === 'Completed').length;
  const taskCompletionRate = Math.round((completedTasksCount / (tasks.length || 1)) * 100);

  const supplierLeadTimes = suppliers.map((s) => ({
    name: s.name.split(' ')[0],
    leadTime: s.leadTimeDays,
    score: s.performanceScore,
  }));

  const handlePrintReport = () => {
    window.print();
  };

  const handleExportCSV = () => {
    const csvContent =
      'data:text/csv;charset=utf-8,' +
      [
        ['Metric', 'Value'],
        ['Total Dispatched Revenue', `$${totalRevenue.toFixed(2)}`],
        ['Total Units Sold', totalUnitsSold],
        ['Catalog Active Products', `${publishedProducts} of ${products.length}`],
        ['Catalog Completion Rate', `${catalogCompletionRate}%`],
        ['Supplier Reliability Score', `${avgSupplierScore}%`],
        ['VA Task Completion Rate', `${taskCompletionRate}%`],
      ]
        .map((e) => e.join(','))
        .join('\n');

    const encodedUri = encodeURI(csvContent);
    const link = document.createElement('a');
    link.setAttribute('href', encodedUri);
    link.setAttribute('download', `va_operations_report_${new Date().toISOString().split('T')[0]}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="bg-white rounded-xl border border-slate-200 p-4 shadow-xs flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 rounded-lg bg-indigo-50 border border-indigo-200 text-indigo-700 flex items-center justify-center font-bold">
            <BarChart3 className="w-5 h-5" />
          </div>
          <div>
            <h2 className="text-base font-bold text-slate-900">
              E-Commerce Operations & Performance Reports
            </h2>
            <p className="text-xs text-slate-500">
              Generated by Catherine Ngina (Virtual Assistant) • Comprehensive monthly audit & KPI reporting
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <select
            value={reportPeriod}
            onChange={(e) => setReportPeriod(e.target.value)}
            className="px-3 py-1.5 text-xs bg-slate-50 border border-slate-200 rounded-lg text-slate-700 font-medium"
          >
            <option value="Last 30 Days">Last 30 Days</option>
            <option value="Last Quarter">Last Quarter</option>
            <option value="Last 6 Months">Last 6 Months (YTD)</option>
            <option value="Annual">Annual Fiscal 2026</option>
          </select>
          <button
            onClick={handleExportCSV}
            className="inline-flex items-center gap-1 px-3 py-1.5 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-lg text-xs font-semibold border border-slate-200 transition-colors cursor-pointer"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Export CSV</span>
          </button>
          <button
            onClick={handlePrintReport}
            className="inline-flex items-center gap-1 px-3.5 py-1.5 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg text-xs font-semibold transition-colors cursor-pointer shadow-xs"
          >
            <Printer className="w-3.5 h-3.5" />
            <span>Print Report</span>
          </button>
        </div>
      </div>

      {/* KPI Cards Summary */}
      <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-3">
        <div className="bg-white rounded-xl border border-slate-200 p-3.5 shadow-2xs">
          <span className="text-[11px] text-slate-500 font-medium block">Total Revenue</span>
          <span className="text-lg font-bold text-slate-900 mt-1 block">${(totalRevenue / 1000).toFixed(1)}k</span>
          <span className="text-[10px] text-emerald-600 font-semibold">+14.8% vs last mo</span>
        </div>

        <div className="bg-white rounded-xl border border-slate-200 p-3.5 shadow-2xs">
          <span className="text-[11px] text-slate-500 font-medium block">Total Units Sold</span>
          <span className="text-lg font-bold text-slate-900 mt-1 block">{totalUnitsSold}</span>
          <span className="text-[10px] text-slate-400 font-medium">across 8 SKUs</span>
        </div>

        <div className="bg-white rounded-xl border border-slate-200 p-3.5 shadow-2xs">
          <span className="text-[11px] text-slate-500 font-medium block">Catalog Active</span>
          <span className="text-lg font-bold text-slate-900 mt-1 block">{catalogCompletionRate}%</span>
          <span className="text-[10px] text-emerald-600 font-semibold">{publishedProducts} Active listings</span>
        </div>

        <div className="bg-white rounded-xl border border-slate-200 p-3.5 shadow-2xs">
          <span className="text-[11px] text-slate-500 font-medium block">Low Stock Ratio</span>
          <span className="text-lg font-bold text-amber-600 mt-1 block">
            {inventory.filter((i) => i.unitsAvailable <= i.reorderThreshold).length} items
          </span>
          <span className="text-[10px] text-amber-600 font-medium">Reorders logged</span>
        </div>

        <div className="bg-white rounded-xl border border-slate-200 p-3.5 shadow-2xs">
          <span className="text-[11px] text-slate-500 font-medium block">Supplier Reliability</span>
          <span className="text-lg font-bold text-emerald-600 mt-1 block">{avgSupplierScore}%</span>
          <span className="text-[10px] text-emerald-600 font-medium">Lead time avg 11d</span>
        </div>

        <div className="bg-white rounded-xl border border-slate-200 p-3.5 shadow-2xs">
          <span className="text-[11px] text-slate-500 font-medium block">VA Tasks Completed</span>
          <span className="text-lg font-bold text-indigo-600 mt-1 block">{taskCompletionRate}%</span>
          <span className="text-[10px] text-indigo-600 font-medium">{completedTasksCount}/{tasks.length} resolved</span>
        </div>
      </div>

      {/* Main Charts Row */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
        {/* Revenue & Orders Growth Chart */}
        <div className="bg-white rounded-xl border border-slate-200 p-5 shadow-xs">
          <div className="flex items-center justify-between mb-4">
            <div>
              <h3 className="text-xs font-bold text-slate-900 uppercase tracking-wide">
                Monthly Revenue & Operational Profit ($)
              </h3>
              <p className="text-xs text-slate-500">6-Month historical performance trajectory</p>
            </div>
            <span className="text-xs font-semibold text-emerald-600 bg-emerald-50 px-2 py-0.5 rounded">
              Average Margin 64.2%
            </span>
          </div>

          <div className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={monthlySalesData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                <defs>
                  <linearGradient id="colorRev" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#3b82f6" stopOpacity={0.4} />
                    <stop offset="95%" stopColor="#3b82f6" stopOpacity={0} />
                  </linearGradient>
                  <linearGradient id="colorProfit" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#10b981" stopOpacity={0.4} />
                    <stop offset="95%" stopColor="#10b981" stopOpacity={0} />
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9" />
                <XAxis dataKey="month" tick={{ fontSize: 11, fill: '#64748b' }} axisLine={false} tickLine={false} />
                <YAxis tick={{ fontSize: 11, fill: '#64748b' }} axisLine={false} tickLine={false} tickFormatter={(v) => `$${v / 1000}k`} />
                <Tooltip
                  contentStyle={{
                    backgroundColor: '#0f172a',
                    border: 'none',
                    borderRadius: '8px',
                    color: '#fff',
                    fontSize: '11px',
                  }}
                  formatter={(val: any) => [`$${Number(val).toLocaleString()}`, '']}
                />
                <Area type="monotone" dataKey="revenue" name="Gross Revenue" stroke="#3b82f6" strokeWidth={2} fillOpacity={1} fill="url(#colorRev)" />
                <Area type="monotone" dataKey="profit" name="Net Profit" stroke="#10b981" strokeWidth={2} fillOpacity={1} fill="url(#colorProfit)" />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Sales by Category Pie & Table */}
        <div className="bg-white rounded-xl border border-slate-200 p-5 shadow-xs">
          <div className="flex items-center justify-between mb-4">
            <div>
              <h3 className="text-xs font-bold text-slate-900 uppercase tracking-wide">
                Revenue Share by Product Category
              </h3>
              <p className="text-xs text-slate-500">Distribution across operational niches</p>
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 items-center gap-4">
            <div className="h-56">
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie
                    data={categorySalesData}
                    dataKey="revenue"
                    nameKey="category"
                    cx="50%"
                    cy="50%"
                    innerRadius={45}
                    outerRadius={75}
                    paddingAngle={4}
                  >
                    {categorySalesData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={CATEGORY_COLORS[index % CATEGORY_COLORS.length]} />
                    ))}
                  </Pie>
                  <Tooltip
                    contentStyle={{
                      backgroundColor: '#0f172a',
                      borderRadius: '8px',
                      color: '#fff',
                      fontSize: '11px',
                    }}
                    formatter={(val: any) => [`$${Number(val).toLocaleString()}`, 'Revenue']}
                  />
                </PieChart>
              </ResponsiveContainer>
            </div>

            <div className="space-y-2 text-xs">
              {categorySalesData.map((item, index) => (
                <div key={item.category} className="flex items-center justify-between p-2 rounded-lg bg-slate-50">
                  <div className="flex items-center gap-2">
                    <div
                      className="w-2.5 h-2.5 rounded-full"
                      style={{ backgroundColor: CATEGORY_COLORS[index % CATEGORY_COLORS.length] }}
                    />
                    <span className="font-medium text-slate-800">{item.category}</span>
                  </div>
                  <span className="font-bold text-slate-900">${item.revenue.toLocaleString()}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* Supplier Performance and SLA Benchmarks */}
      <div className="bg-white rounded-xl border border-slate-200 p-5 shadow-xs">
        <h3 className="text-xs font-bold text-slate-900 uppercase tracking-wide mb-4">
          Supplier Lead Time vs. Quality Audit Scores
        </h3>
        <div className="h-60">
          <ResponsiveContainer width="100%" height="100%">
            <BarChart data={supplierLeadTimes} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
              <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9" />
              <XAxis dataKey="name" tick={{ fontSize: 11, fill: '#64748b' }} axisLine={false} tickLine={false} />
              <YAxis tick={{ fontSize: 11, fill: '#64748b' }} axisLine={false} tickLine={false} />
              <Tooltip
                contentStyle={{
                  backgroundColor: '#0f172a',
                  borderRadius: '8px',
                  color: '#fff',
                  fontSize: '11px',
                }}
              />
              <Bar dataKey="leadTime" name="Lead Time (Days)" fill="#f59e0b" radius={[4, 4, 0, 0]} />
              <Bar dataKey="score" name="Performance Score (%)" fill="#10b981" radius={[4, 4, 0, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </div>
      </div>
    </div>
  );
};
