import {
  Product,
  InventoryItem,
  Order,
  Supplier,
  ProductResearchItem,
  PricingItem,
  VATask,
  MonthlyMetric,
  CategoryMetric,
} from './types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-001',
    name: 'Executive Leather Work Bag',
    sku: 'ELWB-BRN-01',
    category: 'Bags & Accessories',
    supplierId: 'sup-001',
    supplierName: 'Urban Supply Co.',
    costPrice: 42.5,
    sellingPrice: 119.0,
    profitMargin: 64.3,
    currentStock: 38,
    reorderThreshold: 15,
    status: 'Active',
    listingStatus: 'Published',
    description: 'Full-grain vegan leather executive messenger bag with padded 15.6" laptop compartment, water-resistant lining, and brass hardware.',
    listingChannels: ['Shopify Store', 'Amazon US', 'Walmart Marketplace'],
    salesVelocity: 64,
    lastUpdated: '2026-08-25',
    notes: 'Bestseller in Q2/Q3. High customer satisfaction score (4.8/5). Consider adding navy blue variant.',
  },
  {
    id: 'prod-002',
    name: 'Wireless Ergonomic Keyboard',
    sku: 'WEK-RGB-BLK',
    category: 'Computer Peripherals',
    supplierId: 'sup-003',
    supplierName: 'Metro Office Imports',
    costPrice: 28.0,
    sellingPrice: 79.99,
    profitMargin: 65.0,
    currentStock: 9,
    reorderThreshold: 20,
    status: 'Active',
    listingStatus: 'Published',
    description: 'Split curved keyframe wireless keyboard with cushioned wrist rest, dual Bluetooth/2.4G connectivity, and rechargeable 1200mAh battery.',
    listingChannels: ['Shopify Store', 'Amazon US'],
    salesVelocity: 82,
    lastUpdated: '2026-08-26',
    notes: 'Low stock warning triggered yesterday. Supplier lead time is 12 days. Urgent PO recommended.',
  },
  {
    id: 'prod-003',
    name: 'Smart Desk Lamp with Wireless Charger',
    sku: 'SDL-LED-WHT',
    category: 'Home & Office Lighting',
    supplierId: 'sup-002',
    supplierName: 'PrimeGoods Distribution',
    costPrice: 19.5,
    sellingPrice: 54.95,
    profitMargin: 64.5,
    currentStock: 46,
    reorderThreshold: 15,
    status: 'Active',
    listingStatus: 'Published',
    description: 'Dimmable eye-caring LED desk lamp with 5 color temperatures, integrated 15W Qi fast charging base, and auto-off timer.',
    listingChannels: ['Shopify Store', 'Amazon US', 'TikTok Shop'],
    salesVelocity: 45,
    lastUpdated: '2026-08-24',
    notes: 'High conversion rate through social ad campaigns. Stock healthy.',
  },
  {
    id: 'prod-004',
    name: 'Premium Office Chair Ergonomic Mesh',
    sku: 'POC-MESH-GRY',
    category: 'Office Furniture',
    supplierId: 'sup-005',
    supplierName: 'Apex Home Supplies',
    costPrice: 110.0,
    sellingPrice: 289.0,
    profitMargin: 61.9,
    currentStock: 14,
    reorderThreshold: 10,
    status: 'Active',
    listingStatus: 'Published',
    description: 'High-back breathable mesh ergonomic office chair with dynamic lumbar support, 3D adjustable armrests, and 135-degree tilt recline.',
    listingChannels: ['Shopify Store', 'Amazon US'],
    salesVelocity: 31,
    lastUpdated: '2026-08-22',
    notes: 'Bulky item, stored in regional 3PL warehouse B. Freight shipment tracking verified.',
  },
  {
    id: 'prod-005',
    name: 'Portable Aluminum Laptop Stand',
    sku: 'PLS-ALU-SLV',
    category: 'Computer Peripherals',
    supplierId: 'sup-003',
    supplierName: 'Metro Office Imports',
    costPrice: 9.8,
    sellingPrice: 32.5,
    profitMargin: 69.8,
    currentStock: 85,
    reorderThreshold: 25,
    status: 'Active',
    listingStatus: 'Published',
    description: 'Foldable ergonomic aluminum riser stand with 6 adjustable height angles, silicone anti-slip grips, and included velvet travel pouch.',
    listingChannels: ['Shopify Store', 'Amazon US', 'Walmart Marketplace'],
    salesVelocity: 110,
    lastUpdated: '2026-08-26',
    notes: 'Strong bundle candidate with Ergonomic Keyboard and Desk Lamp.',
  },
  {
    id: 'prod-006',
    name: 'Stainless Steel Insulated Water Bottle (32oz)',
    sku: 'SSWB-32OZ-MAT',
    category: 'Drinkware & Lifestyle',
    supplierId: 'sup-004',
    supplierName: 'GreenCart Wholesale',
    costPrice: 6.5,
    sellingPrice: 24.99,
    profitMargin: 74.0,
    currentStock: 120,
    reorderThreshold: 30,
    status: 'Active',
    listingStatus: 'Published',
    description: 'Double-wall vacuum insulated stainless steel canteen keeps beverages cold for 24h or hot for 12h. Leak-proof straw lid and powder coat finish.',
    listingChannels: ['Shopify Store', 'Amazon US'],
    salesVelocity: 95,
    lastUpdated: '2026-08-20',
    notes: 'Solid everyday cashflow generator with high profit margin.',
  },
  {
    id: 'prod-007',
    name: 'Active Noise Cancelling Headphones Over-Ear',
    sku: 'ANCH-BT5-BLK',
    category: 'Audio Electronics',
    supplierId: 'sup-002',
    supplierName: 'PrimeGoods Distribution',
    costPrice: 45.0,
    sellingPrice: 129.99,
    profitMargin: 65.4,
    currentStock: 6,
    reorderThreshold: 20,
    status: 'Needs Review',
    listingStatus: 'Published',
    description: 'Hybrid active noise cancellation headphones with 40mm drivers, transparency mode, 45-hour battery life, and ultra-plush memory foam ear cups.',
    listingChannels: ['Shopify Store', 'Amazon US'],
    salesVelocity: 55,
    lastUpdated: '2026-08-27',
    notes: 'Critical stock level (6 units). Supplier announced a minor price increase to $47.50 starting next month. Need to review pricing.',
  },
  {
    id: 'prod-008',
    name: 'Minimalist Walnut Desk Organizer Tray',
    sku: 'MDO-WLT-04',
    category: 'Desk Accessories',
    supplierId: 'sup-001',
    supplierName: 'Urban Supply Co.',
    costPrice: 12.0,
    sellingPrice: 38.0,
    profitMargin: 68.4,
    currentStock: 52,
    reorderThreshold: 18,
    status: 'Active',
    listingStatus: 'Published',
    description: 'Handcrafted solid walnut multi-tier desktop caddy for pens, mobile devices, keys, and cards with magnetic modular dividers.',
    listingChannels: ['Shopify Store', 'Amazon US', 'Etsy Shop'],
    salesVelocity: 42,
    lastUpdated: '2026-08-23',
    notes: 'Popular holiday gift item. High repeat purchase rate.',
  },
  {
    id: 'prod-009',
    name: 'Ultra-Thin Magnetic Wireless Power Bank 10000mAh',
    sku: 'MWPB-10K-GRY',
    category: 'Mobile Accessories',
    supplierId: 'sup-002',
    supplierName: 'PrimeGoods Distribution',
    costPrice: 16.5,
    sellingPrice: 46.99,
    profitMargin: 64.9,
    currentStock: 0,
    reorderThreshold: 20,
    status: 'Out of Stock',
    listingStatus: 'Pending Approval',
    description: 'MagSafe compatible slim 15W wireless power pack with foldable kickstand, USB-C Power Delivery 20W wired output, and LED power indicator.',
    listingChannels: ['Shopify Store'],
    salesVelocity: 38,
    lastUpdated: '2026-08-25',
    notes: 'Stockout occurred 2 days ago. New batch of 100 units already shipped by PrimeGoods (expected delivery in 4 days).',
  },
  {
    id: 'prod-010',
    name: 'Heavy-Duty Anti-Fatigue Standing Desk Mat',
    sku: 'AFM-MAT-BLK',
    category: 'Office Furniture',
    supplierId: 'sup-005',
    supplierName: 'Apex Home Supplies',
    costPrice: 18.0,
    sellingPrice: 49.5,
    profitMargin: 63.6,
    currentStock: 29,
    reorderThreshold: 15,
    status: 'Active',
    listingStatus: 'Published',
    description: 'High-density commercial grade polyurethane floor mat with beveled anti-trip edges and massage acupressure points.',
    listingChannels: ['Shopify Store', 'Amazon US'],
    salesVelocity: 28,
    lastUpdated: '2026-08-21',
    notes: 'Stable demand. Low return rate (0.8%).',
  },
  {
    id: 'prod-011',
    name: 'Adjustable Dual Monitor Arm Desk Mount',
    sku: 'DMA-GAS-BLK',
    category: 'Computer Peripherals',
    supplierId: 'sup-003',
    supplierName: 'Metro Office Imports',
    costPrice: 34.0,
    sellingPrice: 89.95,
    profitMargin: 62.2,
    currentStock: 8,
    reorderThreshold: 15,
    status: 'Needs Review',
    listingStatus: 'Published',
    description: 'Gas spring dual monitor stand supporting screens up to 32 inches, full 360 degree rotation, integrated cable management routing.',
    listingChannels: ['Shopify Store', 'Amazon US'],
    salesVelocity: 36,
    lastUpdated: '2026-08-27',
    notes: 'Low stock alert. Competitor recently dropped price by $5. Review recommended.',
  },
  {
    id: 'prod-012',
    name: 'Eco-Friendly Bamboo Cable Organizer Box',
    sku: 'BCO-BOX-NAT',
    category: 'Desk Accessories',
    supplierId: 'sup-004',
    supplierName: 'GreenCart Wholesale',
    costPrice: 7.2,
    sellingPrice: 22.99,
    profitMargin: 68.7,
    currentStock: 64,
    reorderThreshold: 20,
    status: 'Active',
    listingStatus: 'Published',
    description: 'Natural bamboo cord hider container with ventilated base and multi-slot routing ports for power strips and adapters.',
    listingChannels: ['Shopify Store', 'Amazon US'],
    salesVelocity: 50,
    lastUpdated: '2026-08-19',
    notes: 'Great eco-conscious addition to office setup category.',
  },
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    productId: 'prod-007',
    sku: 'ANCH-BT5-BLK',
    productName: 'Active Noise Cancelling Headphones Over-Ear',
    category: 'Audio Electronics',
    supplierName: 'PrimeGoods Distribution',
    unitsAvailable: 6,
    unitsSold: 184,
    reorderThreshold: 20,
    reorderStatus: 'Critical Shortage',
    incomingStock: 50,
    daysOfSupply: 3,
    lastRestocked: '2026-07-28',
  },
  {
    productId: 'prod-009',
    sku: 'MWPB-10K-GRY',
    productName: 'Ultra-Thin Magnetic Wireless Power Bank 10000mAh',
    category: 'Mobile Accessories',
    supplierName: 'PrimeGoods Distribution',
    unitsAvailable: 0,
    unitsSold: 215,
    reorderThreshold: 20,
    reorderStatus: 'Order Placed',
    incomingStock: 100,
    daysOfSupply: 0,
    lastRestocked: '2026-07-15',
  },
  {
    productId: 'prod-002',
    sku: 'WEK-RGB-BLK',
    productName: 'Wireless Ergonomic Keyboard',
    category: 'Computer Peripherals',
    supplierName: 'Metro Office Imports',
    unitsAvailable: 9,
    unitsSold: 342,
    reorderThreshold: 20,
    reorderStatus: 'Low Stock Alert',
    incomingStock: 0,
    daysOfSupply: 4,
    lastRestocked: '2026-08-02',
  },
  {
    productId: 'prod-011',
    sku: 'DMA-GAS-BLK',
    productName: 'Adjustable Dual Monitor Arm Desk Mount',
    category: 'Computer Peripherals',
    supplierName: 'Metro Office Imports',
    unitsAvailable: 8,
    unitsSold: 160,
    reorderThreshold: 15,
    reorderStatus: 'Low Stock Alert',
    incomingStock: 30,
    daysOfSupply: 6,
    lastRestocked: '2026-08-05',
  },
  {
    productId: 'prod-004',
    sku: 'POC-MESH-GRY',
    productName: 'Premium Office Chair Ergonomic Mesh',
    category: 'Office Furniture',
    supplierName: 'Apex Home Supplies',
    unitsAvailable: 14,
    unitsSold: 98,
    reorderThreshold: 10,
    reorderStatus: 'Normal',
    incomingStock: 0,
    daysOfSupply: 14,
    lastRestocked: '2026-08-10',
  },
  {
    productId: 'prod-001',
    sku: 'ELWB-BRN-01',
    productName: 'Executive Leather Work Bag',
    category: 'Bags & Accessories',
    supplierName: 'Urban Supply Co.',
    unitsAvailable: 38,
    unitsSold: 289,
    reorderThreshold: 15,
    reorderStatus: 'Normal',
    incomingStock: 0,
    daysOfSupply: 18,
    lastRestocked: '2026-08-14',
  },
  {
    productId: 'prod-003',
    sku: 'SDL-LED-WHT',
    productName: 'Smart Desk Lamp with Wireless Charger',
    category: 'Home & Office Lighting',
    supplierName: 'PrimeGoods Distribution',
    unitsAvailable: 46,
    unitsSold: 310,
    reorderThreshold: 15,
    reorderStatus: 'Normal',
    incomingStock: 0,
    daysOfSupply: 31,
    lastRestocked: '2026-08-15',
  },
  {
    productId: 'prod-008',
    sku: 'MDO-WLT-04',
    productName: 'Minimalist Walnut Desk Organizer Tray',
    category: 'Desk Accessories',
    supplierName: 'Urban Supply Co.',
    unitsAvailable: 52,
    unitsSold: 240,
    reorderThreshold: 18,
    reorderStatus: 'Normal',
    incomingStock: 0,
    daysOfSupply: 37,
    lastRestocked: '2026-08-12',
  },
  {
    productId: 'prod-010',
    sku: 'AFM-MAT-BLK',
    productName: 'Heavy-Duty Anti-Fatigue Standing Desk Mat',
    category: 'Office Furniture',
    supplierName: 'Apex Home Supplies',
    unitsAvailable: 29,
    unitsSold: 135,
    reorderThreshold: 15,
    reorderStatus: 'Normal',
    incomingStock: 0,
    daysOfSupply: 32,
    lastRestocked: '2026-08-08',
  },
  {
    productId: 'prod-005',
    sku: 'PLS-ALU-SLV',
    productName: 'Portable Aluminum Laptop Stand',
    category: 'Computer Peripherals',
    supplierName: 'Metro Office Imports',
    unitsAvailable: 85,
    unitsSold: 460,
    reorderThreshold: 25,
    reorderStatus: 'Normal',
    incomingStock: 0,
    daysOfSupply: 24,
    lastRestocked: '2026-08-18',
  },
  {
    productId: 'prod-006',
    sku: 'SSWB-32OZ-MAT',
    productName: 'Stainless Steel Insulated Water Bottle (32oz)',
    category: 'Drinkware & Lifestyle',
    supplierName: 'GreenCart Wholesale',
    unitsAvailable: 120,
    unitsSold: 580,
    reorderThreshold: 30,
    reorderStatus: 'Normal',
    incomingStock: 0,
    daysOfSupply: 38,
    lastRestocked: '2026-08-11',
  },
  {
    productId: 'prod-012',
    sku: 'BCO-BOX-NAT',
    productName: 'Eco-Friendly Bamboo Cable Organizer Box',
    category: 'Desk Accessories',
    supplierName: 'GreenCart Wholesale',
    unitsAvailable: 64,
    unitsSold: 210,
    reorderThreshold: 20,
    reorderStatus: 'Normal',
    incomingStock: 0,
    daysOfSupply: 38,
    lastRestocked: '2026-08-16',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ORD-8941',
    customerName: 'Eleanor Vance',
    customerEmail: 'eleanor.vance@example.com',
    shippingAddress: '742 Evergreen Terrace, Austin, TX 78701',
    items: [
      { productId: 'prod-001', productName: 'Executive Leather Work Bag', sku: 'ELWB-BRN-01', quantity: 1, unitPrice: 119.0 },
      { productId: 'prod-005', productName: 'Portable Aluminum Laptop Stand', sku: 'PLS-ALU-SLV', quantity: 1, unitPrice: 32.5 },
    ],
    itemsCount: 2,
    date: '2026-08-27 08:42',
    amount: 151.5,
    paymentStatus: 'Paid',
    fulfillmentStatus: 'New',
    priority: 'Rush',
    carrier: 'USPS Priority',
    notes: 'Customer requested eco-friendly packaging if possible.',
  },
  {
    id: 'ORD-8940',
    customerName: 'Marcus Holloway',
    customerEmail: 'marcus.h@example.com',
    shippingAddress: '1204 Pinecrest Blvd, Seattle, WA 98101',
    items: [
      { productId: 'prod-004', productName: 'Premium Office Chair Ergonomic Mesh', sku: 'POC-MESH-GRY', quantity: 1, unitPrice: 289.0 },
      { productId: 'prod-010', productName: 'Heavy-Duty Anti-Fatigue Desk Mat', sku: 'AFM-MAT-BLK', quantity: 1, unitPrice: 49.5 },
    ],
    itemsCount: 2,
    date: '2026-08-27 07:15',
    amount: 338.5,
    paymentStatus: 'Paid',
    fulfillmentStatus: 'Processing',
    priority: 'VIP',
    carrier: 'FedEx Ground',
    trackingNumber: 'FX-849204921US',
    notes: 'High value corporate customer setup.',
  },
  {
    id: 'ORD-8939',
    customerName: 'Sophia Lin',
    customerEmail: 'sophia.lin99@example.com',
    shippingAddress: '450 West End Ave, Apt 7B, New York, NY 10024',
    items: [
      { productId: 'prod-002', productName: 'Wireless Ergonomic Keyboard', sku: 'WEK-RGB-BLK', quantity: 1, unitPrice: 79.99 },
      { productId: 'prod-003', productName: 'Smart Desk Lamp with Wireless Charger', sku: 'SDL-LED-WHT', quantity: 1, unitPrice: 54.95 },
    ],
    itemsCount: 2,
    date: '2026-08-26 18:20',
    amount: 134.94,
    paymentStatus: 'Paid',
    fulfillmentStatus: 'Packed',
    priority: 'Standard',
    carrier: 'UPS Ground',
    trackingNumber: '1Z9999999999999999',
  },
  {
    id: 'ORD-8938',
    customerName: 'Liam O\'Connor',
    customerEmail: 'liam.oc@example.com',
    shippingAddress: '883 Sunset Blvd, Denver, CO 80202',
    items: [
      { productId: 'prod-007', productName: 'Active Noise Cancelling Headphones', sku: 'ANCH-BT5-BLK', quantity: 1, unitPrice: 129.99 },
    ],
    itemsCount: 1,
    date: '2026-08-26 14:10',
    amount: 129.99,
    paymentStatus: 'Paid',
    fulfillmentStatus: 'Shipped',
    priority: 'Standard',
    carrier: 'USPS Priority',
    trackingNumber: '9400100000000000000000',
  },
  {
    id: 'ORD-8937',
    customerName: 'Chloe Bennett',
    customerEmail: 'cbennett@example.com',
    shippingAddress: '312 Ocean View Way, San Diego, CA 92109',
    items: [
      { productId: 'prod-006', productName: 'Stainless Steel Insulated Water Bottle', sku: 'SSWB-32OZ-MAT', quantity: 2, unitPrice: 24.99 },
      { productId: 'prod-008', productName: 'Minimalist Walnut Desk Organizer', sku: 'MDO-WLT-04', quantity: 1, unitPrice: 38.0 },
    ],
    itemsCount: 3,
    date: '2026-08-25 11:32',
    amount: 87.98,
    paymentStatus: 'Paid',
    fulfillmentStatus: 'Delivered',
    priority: 'Standard',
    carrier: 'FedEx Home Delivery',
    trackingNumber: 'FX-339281048US',
  },
  {
    id: 'ORD-8936',
    customerName: 'David K. Morrison',
    customerEmail: 'dmorrison@example.com',
    shippingAddress: '1540 Michigan Ave, Chicago, IL 60605',
    items: [
      { productId: 'prod-011', productName: 'Adjustable Dual Monitor Arm', sku: 'DMA-GAS-BLK', quantity: 1, unitPrice: 89.95 },
      { productId: 'prod-012', productName: 'Bamboo Cable Organizer Box', sku: 'BCO-BOX-NAT', quantity: 1, unitPrice: 22.99 },
    ],
    itemsCount: 2,
    date: '2026-08-25 09:05',
    amount: 112.94,
    paymentStatus: 'Paid',
    fulfillmentStatus: 'Delivered',
    priority: 'Standard',
    carrier: 'UPS Ground',
    trackingNumber: '1Z8888888888888888',
  },
  {
    id: 'ORD-8935',
    customerName: 'Rachel Green',
    customerEmail: 'rachel.g@example.com',
    shippingAddress: '55 Central Park West, New York, NY 10023',
    items: [
      { productId: 'prod-001', productName: 'Executive Leather Work Bag', sku: 'ELWB-BRN-01', quantity: 1, unitPrice: 119.0 },
    ],
    itemsCount: 1,
    date: '2026-08-24 16:45',
    amount: 119.0,
    paymentStatus: 'Refunded',
    fulfillmentStatus: 'Cancelled',
    priority: 'Standard',
    notes: 'Customer ordered wrong color variant and requested immediate cancellation before dispatch.',
  },
];

export const INITIAL_SUPPLIERS: Supplier[] = [
  {
    id: 'sup-001',
    name: 'Urban Supply Co.',
    category: 'Leather Goods & Desk Decor',
    productCount: 4,
    contactPerson: 'David Sterling (Account Director)',
    email: 'orders@urbansupplyco.com',
    phone: '+1 (415) 555-0142',
    leadTimeDays: 8,
    status: 'Active',
    lastOrderDate: '2026-08-14',
    performanceScore: 98,
    rating: 4.9,
    minimumOrderQty: 25,
    paymentTerms: 'Net 30',
  },
  {
    id: 'sup-002',
    name: 'PrimeGoods Distribution',
    category: 'Consumer Electronics & Lighting',
    productCount: 6,
    contactPerson: 'Sarah Jenkins (B2B Lead)',
    email: 'b2b@primegoodsdist.com',
    phone: '+1 (312) 555-0198',
    leadTimeDays: 14,
    status: 'Active',
    lastOrderDate: '2026-08-15',
    performanceScore: 94,
    rating: 4.7,
    minimumOrderQty: 50,
    paymentTerms: 'Net 45',
  },
  {
    id: 'sup-003',
    name: 'Metro Office Imports',
    category: 'Computer Peripherals & Mounts',
    productCount: 5,
    contactPerson: 'Kenji Takahashi (Export Manager)',
    email: 'contact@metroofficeimports.com',
    phone: '+1 (206) 555-0177',
    leadTimeDays: 12,
    status: 'Active',
    lastOrderDate: '2026-08-18',
    performanceScore: 96,
    rating: 4.8,
    minimumOrderQty: 30,
    paymentTerms: 'Net 30',
  },
  {
    id: 'sup-004',
    name: 'GreenCart Wholesale',
    category: 'Eco Lifestyle & Drinkware',
    productCount: 3,
    contactPerson: 'Amara Patel (Operations)',
    email: 'sales@greencartwholesale.com',
    phone: '+1 (503) 555-0164',
    leadTimeDays: 7,
    status: 'Active',
    lastOrderDate: '2026-08-16',
    performanceScore: 99,
    rating: 5.0,
    minimumOrderQty: 40,
    paymentTerms: 'Net 30',
  },
  {
    id: 'sup-005',
    name: 'Apex Home Supplies',
    category: 'Ergonomic Furniture & Mats',
    productCount: 4,
    contactPerson: 'Robert Hayes (Wholesale Rep)',
    email: 'wholesale@apexhome.com',
    phone: '+1 (770) 555-0131',
    leadTimeDays: 16,
    status: 'Active',
    lastOrderDate: '2026-08-10',
    performanceScore: 91,
    rating: 4.5,
    minimumOrderQty: 10,
    paymentTerms: 'Net 60',
  },
];

export const INITIAL_RESEARCH: ProductResearchItem[] = [
  {
    id: 'res-001',
    productName: 'Self-Heating Ceramic Coffee Mug with Charging Coaster',
    category: 'Desk Accessories',
    marketDemand: 'Very High',
    searchVolumeMonthly: 48500,
    competitorPrice: 89.99,
    suggestedSellingPrice: 74.99,
    supplierCost: 23.5,
    estimatedMargin: 68.7,
    researchStatus: 'Approved',
    pros: ['Extremely high gifting appeal for Q4', 'Healthy 68%+ gross margin', 'Samples tested passed temperature calibration'],
    cons: ['Requires UL safety certified adapter', 'Electronics warranty support required'],
    targetAudience: 'Remote workers, coffee enthusiasts, corporate gifting managers',
    sourceUrl: 'https://supplier-portal.example/products/heat-mug-v2',
    notes: 'Approved by store owner. Ready for Catherine to draft listing copy and request initial 50 unit trial PO.',
    dateAdded: '2026-08-22',
  },
  {
    id: 'res-002',
    productName: 'Under-Desk Walking Pad Treadmill with Remote',
    category: 'Fitness & Home Office',
    marketDemand: 'High',
    searchVolumeMonthly: 82000,
    competitorPrice: 249.0,
    suggestedSellingPrice: 219.0,
    supplierCost: 88.0,
    estimatedMargin: 59.8,
    researchStatus: 'Reviewed',
    pros: ['Very strong search trend and TikTok virality', 'High average order value', 'Complements standing desk mats'],
    cons: ['Heavy shipping costs ($24-32 per unit)', 'Higher return probability if motor issues arise'],
    targetAudience: 'Work-from-home professionals seeking daily step counts',
    sourceUrl: 'https://supplier-portal.example/fitness/pad-100',
    notes: 'Freight shipping quotes calculated from Apex Home Supplies. Need owner sign-off on return logistics.',
    dateAdded: '2026-08-24',
  },
  {
    id: 'res-003',
    productName: 'Magnetic Silicone Cable Clips (6-Pack Multi-Color)',
    category: 'Desk Accessories',
    marketDemand: 'Moderate',
    searchVolumeMonthly: 21000,
    competitorPrice: 14.99,
    suggestedSellingPrice: 12.99,
    supplierCost: 2.1,
    estimatedMargin: 83.8,
    researchStatus: 'Researching',
    pros: ['Extremely lightweight shipping', 'Excellent 83% margin', 'Perfect order-bump / cart upsell item'],
    cons: ['Low standalone ticket value ($12.99)'],
    targetAudience: 'Desk aesthetic enthusiasts, students, tech professionals',
    notes: 'Testing sample adhesives for residue-free removal. Requesting bulk sample pack from GreenCart Wholesale.',
    dateAdded: '2026-08-26',
  },
  {
    id: 'res-004',
    productName: 'Ultra-Quiet Ultrasonic Cool Mist Desk Humidifier',
    category: 'Home & Office Lighting',
    marketDemand: 'Seasonal',
    searchVolumeMonthly: 34000,
    competitorPrice: 34.5,
    suggestedSellingPrice: 29.99,
    supplierCost: 8.9,
    estimatedMargin: 70.3,
    researchStatus: 'Needs Review',
    pros: ['High seasonal demand approaching Fall/Winter', 'Compact form factor fits beside monitors'],
    cons: ['Water leakage risk if tilted', 'Need clear maintenance instructions'],
    targetAudience: 'Office workers in air-conditioned or dry winter environments',
    notes: 'Investigating whether supplier provides leak-tested silicone gaskets before final decision.',
    dateAdded: '2026-08-25',
  },
  {
    id: 'res-005',
    productName: 'Ergonomic Memory Foam Footrest Cushion',
    category: 'Office Furniture',
    marketDemand: 'Moderate',
    searchVolumeMonthly: 19500,
    competitorPrice: 39.99,
    suggestedSellingPrice: 34.99,
    supplierCost: 9.2,
    estimatedMargin: 73.7,
    researchStatus: 'Approved',
    pros: ['High margin, vacuum-packed compressed shipping saves 60% freight volume', 'High customer satisfaction'],
    cons: ['Takes 24 hours to fully expand after unboxing'],
    targetAudience: 'Desk workers with lower back tension or shorter leg postures',
    notes: 'Listing imagery drafted. Ready for catalog upload once packaging inserts are finalized.',
    dateAdded: '2026-08-21',
  },
];

export const INITIAL_PRICING: PricingItem[] = [
  {
    productId: 'prod-001',
    productName: 'Executive Leather Work Bag',
    sku: 'ELWB-BRN-01',
    category: 'Bags & Accessories',
    currentCost: 42.5,
    currentPrice: 119.0,
    competitorAverage: 124.5,
    profitMargin: 64.3,
    recommendedPrice: 119.0,
    pricingStatus: 'Competitive',
    priceDelta: -5.5,
    actionRecommendation: 'Maintain current price. Sweet spot for premium perceived value and sales velocity.',
  },
  {
    productId: 'prod-002',
    productName: 'Wireless Ergonomic Keyboard',
    sku: 'WEK-RGB-BLK',
    category: 'Computer Peripherals',
    currentCost: 28.0,
    currentPrice: 79.99,
    competitorAverage: 74.99,
    profitMargin: 65.0,
    recommendedPrice: 76.99,
    pricingStatus: 'Above Market',
    priceDelta: +5.0,
    actionRecommendation: 'Competitors discount during back-to-school. Test slight adjustment to $76.99.',
  },
  {
    productId: 'prod-007',
    productName: 'Active Noise Cancelling Headphones Over-Ear',
    sku: 'ANCH-BT5-BLK',
    category: 'Audio Electronics',
    currentCost: 45.0,
    currentPrice: 129.99,
    competitorAverage: 149.0,
    profitMargin: 65.4,
    recommendedPrice: 139.0,
    pricingStatus: 'Below Market',
    priceDelta: -19.01,
    actionRecommendation: 'We are under-pricing versus market leaders. Supplier cost increasing; raise to $139.00 to preserve 66% margin.',
  },
  {
    productId: 'prod-005',
    productName: 'Portable Aluminum Laptop Stand',
    sku: 'PLS-ALU-SLV',
    category: 'Computer Peripherals',
    currentCost: 9.8,
    currentPrice: 32.5,
    competitorAverage: 31.99,
    profitMargin: 69.8,
    recommendedPrice: 32.5,
    pricingStatus: 'Competitive',
    priceDelta: +0.51,
    actionRecommendation: 'Price is balanced with high 69.8% margin and #1 ranking in search tags.',
  },
  {
    productId: 'prod-011',
    productName: 'Adjustable Dual Monitor Arm Desk Mount',
    sku: 'DMA-GAS-BLK',
    category: 'Computer Peripherals',
    currentCost: 34.0,
    currentPrice: 89.95,
    competitorAverage: 84.99,
    profitMargin: 62.2,
    recommendedPrice: 84.95,
    pricingStatus: 'Needs Review',
    priceDelta: +4.96,
    actionRecommendation: 'Conversion dipped 4% last week due to competitor flash sale at $84.99. Reprice to $84.95.',
  },
  {
    productId: 'prod-006',
    productName: 'Stainless Steel Insulated Water Bottle (32oz)',
    sku: 'SSWB-32OZ-MAT',
    category: 'Drinkware & Lifestyle',
    currentCost: 6.5,
    currentPrice: 24.99,
    competitorAverage: 25.5,
    profitMargin: 74.0,
    recommendedPrice: 24.99,
    pricingStatus: 'Competitive',
    priceDelta: -0.51,
    actionRecommendation: 'Top margin performer. Keep price stable and offer buy 2 get 10% off bundle.',
  },
];

export const INITIAL_TASKS: VATask[] = [
  {
    id: 'tsk-101',
    title: 'Update 25 product descriptions with SEO keywords & bullet points',
    description: 'Optimize product copy for Bags & Accessories category with target search phrases, specs table, and dimensions.',
    assignedTo: 'Catherine Ngina (VA)',
    category: 'Catalog',
    priority: 'High',
    dueDate: '2026-08-28',
    status: 'In Progress',
    relatedEntity: 'Product Catalog',
  },
  {
    id: 'tsk-102',
    title: 'Verify supplier pricing & shipping lead times for Q4',
    description: 'Reach out to Urban Supply Co. and PrimeGoods Distribution to confirm volume tier discounts and peak season cutoffs.',
    assignedTo: 'Catherine Ngina (VA)',
    category: 'Supplier',
    priority: 'Urgent',
    dueDate: '2026-08-29',
    status: 'To Do',
    relatedEntity: 'PrimeGoods & Urban Supply',
  },
  {
    id: 'tsk-103',
    title: 'Upload new lifestyle & infographic images for ANC Headphones',
    description: 'Replace standard manufacturer render with custom dimensions infographic, battery comparison chart, and carrying case photo.',
    assignedTo: 'Catherine Ngina (VA)',
    category: 'Catalog',
    priority: 'Medium',
    dueDate: '2026-08-30',
    status: 'To Do',
    relatedEntity: 'ANCH-BT5-BLK',
  },
  {
    id: 'tsk-104',
    title: 'Check low-stock products & generate replenishment PO drafts',
    description: 'Monitor stock levels for 24 low-stock items. Create draft Purchase Orders in supplier portal for manager approval.',
    assignedTo: 'Catherine Ngina (VA)',
    category: 'Inventory',
    priority: 'High',
    dueDate: '2026-08-27',
    status: 'Completed',
    relatedEntity: 'Inventory Management',
    completedAt: '2026-08-27 09:15',
  },
  {
    id: 'tsk-105',
    title: 'Review competitor pricing on Dual Monitor Arm & Ergonomic Keyboards',
    description: 'Benchmark top 5 Amazon sellers and direct DTC competitor stores; propose margin-preserving adjustments in Pricing Hub.',
    assignedTo: 'Catherine Ngina (VA)',
    category: 'Admin',
    priority: 'Medium',
    dueDate: '2026-08-28',
    status: 'Review',
    relatedEntity: 'Pricing Dashboard',
  },
  {
    id: 'tsk-106',
    title: 'Update discontinued listings & archive out-of-season tags',
    description: 'Archive 12 retired SKU variants, delist dead links on Shopify, and update internal inventory records.',
    assignedTo: 'Catherine Ngina (VA)',
    category: 'Catalog',
    priority: 'Low',
    dueDate: '2026-08-31',
    status: 'To Do',
    relatedEntity: 'Catalog Archive',
  },
  {
    id: 'tsk-107',
    title: 'Process pending rush orders & verify address validity',
    description: 'Audit 37 pending queue orders for high fraud score flags, address autocomplete errors, and release to warehouse 3PL.',
    assignedTo: 'Catherine Ngina (VA)',
    category: 'Orders',
    priority: 'Urgent',
    dueDate: '2026-08-27',
    status: 'In Progress',
    relatedEntity: 'Order Queue',
  },
];

export const MONTHLY_METRICS: MonthlyMetric[] = [
  { month: 'Mar', revenue: 38200, orders: 224, profit: 24830, avgOrderValue: 170.5 },
  { month: 'Apr', revenue: 41500, orders: 248, profit: 26975, avgOrderValue: 167.3 },
  { month: 'May', revenue: 44100, orders: 260, profit: 28665, avgOrderValue: 169.6 },
  { month: 'Jun', revenue: 46800, orders: 275, profit: 30420, avgOrderValue: 170.1 },
  { month: 'Jul', revenue: 45200, orders: 268, profit: 29380, avgOrderValue: 168.6 },
  { month: 'Aug (MTD)', revenue: 48620, orders: 286, profit: 31603, avgOrderValue: 170.0 },
];

export const DAILY_ORDERS_TREND = [
  { day: 'Aug 21', orders: 12, revenue: 1980 },
  { day: 'Aug 22', orders: 15, revenue: 2540 },
  { day: 'Aug 23', orders: 18, revenue: 3120 },
  { day: 'Aug 24', orders: 14, revenue: 2410 },
  { day: 'Aug 25', orders: 16, revenue: 2780 },
  { day: 'Aug 26', orders: 21, revenue: 3650 },
  { day: 'Aug 27', orders: 19, revenue: 3240 },
];

export const CATEGORY_METRICS: CategoryMetric[] = [
  { category: 'Computer Peripherals', sales: 14850, units: 284, percentage: 30.5, margin: 66.2 },
  { category: 'Office Furniture', sales: 12400, units: 68, percentage: 25.5, margin: 62.4 },
  { category: 'Bags & Accessories', sales: 9650, units: 102, percentage: 19.8, margin: 65.5 },
  { category: 'Audio Electronics', sales: 6240, units: 58, percentage: 12.8, margin: 65.4 },
  { category: 'Desk Accessories & Other', sales: 5480, units: 196, percentage: 11.4, margin: 71.0 },
];

export const INVENTORY_STATUS_DATA = [
  { name: 'Healthy Stock (85%)', value: 1042, color: '#10b981' },
  { name: 'Low Stock (1.9%)', value: 24, color: '#f59e0b' },
  { name: 'Critical Shortage (0.6%)', value: 8, color: '#ef4444' },
  { name: 'Reorder Placed (12.5%)', value: 156, color: '#3b82f6' },
  { name: 'Out of Stock (1.4%)', value: 18, color: '#6b7280' },
];

export const vaWorkflowSteps = [
  {
    stepNumber: 1,
    title: 'Product Opportunity Research',
    subtitle: 'Niche Analysis & Demand Sourcing',
    description: 'Catherine monitors search trends, analyzes competitor margins, and assesses sourcing feasibility.',
    vaResponsibilities: [
      'Conduct keyword volume and demand audits on Amazon, Google Shopping, and TikTok trends',
      'Verify target profit margins exceed the store minimum threshold of 60%',
      'Review supplier production lead times, MOQ requirements, and customer reviews',
      'Submit formal sourcing dossiers with pros/cons and risk factors',
    ],
    targetSection: 'research' as const,
    badgeText: 'Step 1 • Sourcing',
  },
  {
    stepNumber: 2,
    title: 'Supplier Negotiation & Terms',
    subtitle: 'Lead Time & Quality Benchmarks',
    description: 'Vet manufacturing partners, establish sample orders, and negotiate Net 30/60 terms.',
    vaResponsibilities: [
      'Verify supplier business registrations and factory quality audit certifications',
      'Draft formal Request for Quotes (RFQs) and negotiate volume pricing tiers',
      'Track sample dispatch schedules and evaluate build quality before mass listing',
      'Maintain active contact logs with primary and backup manufacturing partners',
    ],
    targetSection: 'suppliers' as const,
    badgeText: 'Step 2 • Procurement',
  },
  {
    stepNumber: 3,
    title: 'Catalog Listing Optimization',
    subtitle: 'SEO Copywriting, Visuals & Specs',
    description: 'Transform raw specifications into high-converting e-commerce listings with structured tags.',
    vaResponsibilities: [
      'Write persuasive, benefit-driven product titles, bullet points, and descriptions',
      'Integrate high-intent SEO keywords to improve organic search discoverability',
      'Coordinate lifestyle photos, infographic dimensions, and package renders',
      'Assign SKUs, barcode standards, and multi-channel categorization',
    ],
    targetSection: 'products' as const,
    badgeText: 'Step 3 • Merchandising',
  },
  {
    stepNumber: 4,
    title: 'Competitive Repricing & Margin Hub',
    subtitle: 'Market Benchmarking & Dynamic Pricing',
    description: 'Keep prices competitive against marketplace fluctuations while preserving target profitability.',
    vaResponsibilities: [
      'Scrape and benchmark top 5 competitor listing price points bi-weekly',
      'Model price elasticity against gross profit margins and advertising costs',
      'Execute price adjustments to capture Buy Box advantages',
      'Propose promotional discount bundles and seasonal promotional vouchers',
    ],
    targetSection: 'pricing' as const,
    badgeText: 'Step 4 • Pricing',
  },
  {
    stepNumber: 5,
    title: 'Inventory Forecasting & Reorders',
    subtitle: 'Low-Stock Audits & PO Dispatch',
    description: 'Prevent out-of-stock revenue loss with proactive replenishment calculations.',
    vaResponsibilities: [
      'Calculate daily sales velocity and days-of-supply projections for all SKUs',
      'Trigger replenishment alerts when inventory breaches safety buffer thresholds',
      'Prepare and dispatch standardized Purchase Orders to suppliers with tracking cutoffs',
      'Coordinate with 3PL freight forwarders to expedite customs clearance',
    ],
    targetSection: 'inventory' as const,
    badgeText: 'Step 5 • Stock Control',
  },
  {
    stepNumber: 6,
    title: 'Order Dispatch & 3PL Logistics',
    subtitle: 'Fulfillment Routing & Tracking Sync',
    description: 'Ensure rapid turnaround from customer checkout to carrier dispatch and tracking notifications.',
    vaResponsibilities: [
      'Audit incoming orders for payment confirmation and address validation',
      'Route orders to 3PL warehouse management systems for packing and labeling',
      'Upload carrier tracking numbers to customer notification queues',
      'Handle RMA returns, customer exchange requests, and shipping claims',
    ],
    targetSection: 'orders' as const,
    badgeText: 'Step 6 • Fulfillment',
  },
  {
    stepNumber: 7,
    title: 'Operational Task Management',
    subtitle: 'Task Queues & Daily Checklists',
    description: 'Organize high-priority operational workflows to ensure SLA compliance across all channels.',
    vaResponsibilities: [
      'Maintain prioritized daily task queue across catalog, inventory, and supplier operations',
      'Collaborate with store owners through clear asynchronous status documentation',
      'Perform quality checks on newly published listings and active promotions',
      'Execute routine database maintenance and archive retired SKU variants',
    ],
    targetSection: 'tasks' as const,
    badgeText: 'Step 7 • Operations',
  },
  {
    stepNumber: 8,
    title: 'Executive Reporting & Analytics',
    subtitle: 'Performance Audits & Growth KPIs',
    description: 'Deliver actionable business intelligence, sales trends, and operational efficiency summaries.',
    vaResponsibilities: [
      'Generate weekly/monthly executive revenue, unit volume, and gross profit reports',
      'Analyze return rates, supplier lead-time compliance, and fulfillment SLAs',
      'Identify top-performing bestseller items and underperforming product lines',
      'Formulate strategic recommendations for store catalog expansion',
    ],
    targetSection: 'reports' as const,
    badgeText: 'Step 8 • Analytics',
  },
];

export const initialNotifications = [
  {
    id: 'notif-1',
    title: 'Low Stock Alert: ANC Headphones',
    message: 'Active Noise Cancelling Headphones (ANCH-BT5-BLK) has reached 6 units remaining (Threshold: 12). Draft PO generated.',
    time: '15m ago',
    type: 'urgent' as const,
    read: false,
    actionSection: 'inventory' as const,
  },
  {
    id: 'notif-2',
    title: 'Product Research Approved',
    message: 'Ergonomic Silicone Mouse Wrist Rest passed feasibility audit with 73.3% estimated margin.',
    time: '1h ago',
    type: 'success' as const,
    read: false,
    actionSection: 'research' as const,
  },
  {
    id: 'notif-3',
    title: 'New Rush Order Logged',
    message: 'Order ORD-9418 ($259.98) flagged as Rush priority for immediate 3PL packaging dispatch.',
    time: '2h ago',
    type: 'info' as const,
    read: false,
    actionSection: 'orders' as const,
  },
  {
    id: 'notif-4',
    title: 'Supplier Lead Time Updated',
    message: 'Metro Office Imports confirmed standard lead time reduced to 10 business days for Q4.',
    time: '1d ago',
    type: 'info' as const,
    read: true,
    actionSection: 'suppliers' as const,
  },
];

// Re-export aliases
export const initialProducts = INITIAL_PRODUCTS;
export const initialOrders = INITIAL_ORDERS;
export const initialInventory = INITIAL_INVENTORY;
export const initialSuppliers = INITIAL_SUPPLIERS;
export const initialResearchItems = INITIAL_RESEARCH;
export const initialPricingItems = INITIAL_PRICING;
export const initialTasks = INITIAL_TASKS;
export const monthlySalesData = MONTHLY_METRICS;
export const categorySalesData = CATEGORY_METRICS;

